version: '3'

services:
  mysql-standalone:
    image: 'mysql:8'
    environment:
      - MYSQL_ROOT_HOST='%'
      - MYSQL_DATABASE="hotel_db"
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_PASSWORD="testtest"
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: avito-test-task
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/hotel_db?autoRecconect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "testtest"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
        - mysql-standalone