spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_db?useUnicode=true&
      useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: testtest
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
spring.h2.console.enable: true
spring.flyway.enabled: true
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect

server.port: 8080